export const dummyRecipes: Recipe[] = [
  {
    id: "rec-001", // Added unique ID
    name: "Classic Spaghetti Bolognese",
    description: "A rich and hearty Italian meat sauce served over spaghetti.",
    image: "https://placehold.co/600x400/FF5733/FFFFFF.png?text=Bolognese",
    labels: [
      { category: "Cuisine", name: "Italian" },
      { category: "Meal Type", name: "Dinner" },
      { category: "Diet", name: "Meat" },
      { category: "Difficulty", name: "Medium" },
    ],
    ingredients: [
      { name: "Ground Beef", quantity: "500g" },
      { name: "Canned Tomatoes", quantity: "800g" },
      { name: "Onion", quantity: "1 large" },
      { name: "Carrot", quantity: "1 medium" },
      { name: "Celery Stalk", quantity: "1" },
      { name: "Garlic Cloves", quantity: "2" },
      { name: "Red Wine", quantity: "100ml" },
      { name: "Beef Broth", quantity: "200ml" },
      { name: "Spaghetti", quantity: "400g" },
      { name: "Olive Oil", quantity: "2 tbsp" },
      { name: "Salt", quantity: "to taste" },
      { name: "Black Pepper", quantity: "to taste" },
    ],
    instructions:
      "1. Heat olive oil in a large pot. Add chopped onion, carrot, and celery; cook until softened. 2. Add ground beef and brown evenly. Drain excess fat. 3. Stir in minced garlic, cook for 1 minute. 4. Pour in red wine and simmer until reduced. 5. Add canned tomatoes, beef broth, salt, and pepper. Bring to a simmer, then cover and cook on low for at least 1.5 hours (preferably 3+ hours) for flavors to meld. 6. Cook spaghetti according to package directions. 7. Serve bolognese sauce over hot spaghetti, optionally garnished with Parmesan cheese.",
  },
  {
    id: "rec-002", // Added unique ID
    name: "Vegan Lentil Soup",
    description: "A comforting and nutritious plant-based lentil soup, perfect for a cold day.",
    image: "https://placehold.co/600x400/33FF57/FFFFFF.png?text=Lentil+Soup",
    labels: [
      { category: "Cuisine", name: "Mediterranean" },
      { category: "Meal Type", name: "Lunch" },
      { category: "Diet", name: "Vegan" },
      { category: "Diet", name: "Gluten-Free" },
      { category: "Difficulty", name: "Easy" },
    ],
    ingredients: [
      { name: "Brown Lentils", quantity: "200g" },
      { name: "Vegetable Broth", quantity: "1.5 litres" },
      { name: "Onion", quantity: "1 medium" },
      { name: "Carrots", quantity: "2 medium" },
      { name: "Celery Stalks", quantity: "2" },
      { name: "Garlic Cloves", quantity: "3" },
      { name: "Diced Tomatoes", quantity: "400g can" },
      { name: "Spinach", quantity: "100g" },
      { name: "Cumin", quantity: "1 tsp" },
      { name: "Coriander", quantity: "1 tsp" },
      { name: "Olive Oil", quantity: "1 tbsp" },
      { name: "Salt", quantity: "to taste" },
      { name: "Black Pepper", quantity: "to taste" },
    ],
    instructions:
      "1. Rinse lentils thoroughly. 2. In a large pot, heat olive oil over medium heat. Add chopped onion, carrots, and celery; sauté until softened, about 5-7 minutes. 3. Add minced garlic, cumin, and coriander; cook for 1 minute until fragrant. 4. Stir in rinsed lentils, vegetable broth, and diced tomatoes. Bring to a boil, then reduce heat, cover, and simmer for 25-30 minutes, or until lentils are tender. 5. Stir in fresh spinach until wilted. Season with salt and pepper to taste. Serve hot.",
  },
  {
    id: "rec-003", // Added unique ID
    name: "Chicken Tikka Masala",
    description: "Creamy, spiced chicken curry, a popular Indian dish.",
    image: "https://placehold.co/600x400/FFB833/FFFFFF.png?text=Tikka+Masala",
    labels: [
      { category: "Cuisine", name: "Indian" },
      { category: "Meal Type", name: "Dinner" },
      { category: "Diet", name: "Meat" },
      { category: "Difficulty", name: "Medium" },
    ],
    ingredients: [
      { name: "Chicken Breast", quantity: "600g" },
      { name: "Plain Yogurt", quantity: "150g" },
      { name: "Ginger-Garlic Paste", quantity: "1 tbsp" },
      { name: "Turmeric Powder", quantity: "0.5 tsp" },
      { name: "Chili Powder", quantity: "1 tsp" },
      { name: "Garam Masala", quantity: "1 tsp" },
      { name: "Cumin Powder", "quantity": "1 tsp" },
      { name: "Coriander Powder", quantity: "1 tsp" },
      { name: "Tomato Puree", quantity: "200g" },
      { name: "Heavy Cream", quantity: "100ml" },
      { name: "Onion", quantity: "1 medium" },
      { name: "Butter", quantity: "2 tbsp" },
      { name: "Salt", quantity: "to taste" },
      { name: "Black Pepper", quantity: "to taste" },
    ],
    instructions:
      "1. Cut chicken into bite-sized pieces. Marinate chicken with yogurt, ginger-garlic paste, turmeric, chili powder, garam masala, cumin, coriander, and salt for at least 30 minutes. 2. In a pan, melt butter. Sauté chopped onion until golden. 3. Add marinated chicken and cook until browned. 4. Stir in tomato puree and simmer for 5 minutes. 5. Add heavy cream and cook until sauce thickens. Serve with rice or naan.",
  },
  {
    id: "rec-004", // Added unique ID
    name: "Homemade Pizza Margherita",
    description: "A classic Neapolitan pizza with simple, fresh ingredients.",
    image: "https://placehold.co/600x400/FF33A1/FFFFFF.png?text=Pizza+Margherita",
    labels: [
      { category: "Cuisine", name: "Italian" },
      { category: "Meal Type", name: "Dinner" },
      { category: "Diet", name: "Vegetarian" },
      { category: "Difficulty", name: "Medium" },
    ],
    ingredients: [
      { name: "Pizza Dough", quantity: "400g" },
      { name: "San Marzano Tomatoes", quantity: "400g can" },
      { name: "Fresh Mozzarella", quantity: "200g" },
      { name: "Fresh Basil Leaves", quantity: "a handful" },
      { name: "Olive Oil", quantity: "2 tbsp" },
      { name: "Salt", quantity: "to taste" },
    ],
    instructions:
      "1. Preheat oven to 250°C (480°F) with a pizza stone or baking steel if possible. 2. Stretch dough into a round shape. 3. Crush canned tomatoes with your hands and spread evenly over the dough, leaving a crust. Season with salt. 4. Tear mozzarella into pieces and scatter over the sauce. 5. Drizzle with olive oil. 6. Bake for 8-12 minutes, or until crust is golden and cheese is bubbly. 7. Garnish with fresh basil leaves before serving.",
  },
  {
    id: "rec-005", // Added unique ID
    name: "Quick Chicken Stir-Fry",
    description: "A fast and flavorful stir-fry with chicken and mixed vegetables.",
    image: "https://placehold.co/600x400/33A1FF/FFFFFF.png?text=Stir-Fry",
    labels: [
      { category: "Cuisine", name: "Asian" },
      { category: "Meal Type", name: "Dinner" },
      { category: "Diet", name: "Meat" },
      { category: "Difficulty", name: "Easy" },
      { category: "Cooking Method", name: "Stir-Fry" },
    ],
    ingredients: [
      { name: "Chicken Breast", quantity: "400g" },
      { name: "Broccoli Florets", quantity: "200g" },
      { name: "Carrots", quantity: "1 large" },
      { name: "Bell Peppers (any color)", quantity: "1" },
      { name: "Soy Sauce", quantity: "3 tbsp" },
      { name: "Sesame Oil", quantity: "1 tbsp" },
      { name: "Ginger (grated)", quantity: "1 tsp" },
      { name: "Garlic (minced)", quantity: "2 cloves" },
      { name: "Cornstarch", quantity: "1 tsp" },
      { name: "Water", quantity: "2 tbsp" },
      { name: "Vegetable Oil", quantity: "1 tbsp" },
    ],
    instructions:
      "1. Slice chicken into thin strips. Prepare all vegetables. 2. In a small bowl, whisk together soy sauce, sesame oil, ginger, garlic, cornstarch, and water to make the sauce. 3. Heat vegetable oil in a large wok or skillet over high heat. Add chicken and stir-fry until cooked through. Remove chicken and set aside. 4. Add broccoli, carrots, and bell peppers to the wok. Stir-fry for 3-5 minutes until tender-crisp. 5. Return chicken to the wok. Pour in the sauce and stir quickly until it thickens and coats everything. Serve immediately with rice or noodles.",
  },
  {
    id: "rec-006", // Added unique ID
    name: "Berry Smoothie Bowl",
    description: "A refreshing and healthy breakfast bowl topped with fresh fruits and granola.",
    image: "https://placehold.co/600x400/8A2BE2/FFFFFF.png?text=Smoothie+Bowl",
    labels: [
      { category: "Meal Type", name: "Breakfast" },
      { category: "Diet", name: "Vegetarian" },
      { category: "Diet", name: "Gluten-Free" },
      { category: "Difficulty", name: "Very Easy" },
    ],
    ingredients: [
      { name: "Mixed Berries (frozen)", quantity: "150g" },
      { name: "Banana (frozen)", quantity: "1" },
      { name: "Almond Milk", quantity: "100ml" },
      { name: "Spinach (optional)", quantity: "30g" },
      { name: "Granola", quantity: "30g" },
      { name: "Fresh Berries", quantity: "a handful" },
      { name: "Chia Seeds", quantity: "1 tsp" },
    ],
    instructions:
      "1. Combine frozen mixed berries, frozen banana, almond milk, and optional spinach in a blender. Blend until smooth and thick. Add more almond milk if needed to reach desired consistency. 2. Pour smoothie into a bowl. 3. Top with granola, fresh berries, and chia seeds. Serve immediately.",
  },
  {
    id: "rec-007", // Added unique ID
    name: "Classic French Onion Soup",
    description: "Rich, savory onion soup topped with a cheesy bread crouton.",
    image: "https://placehold.co/600x400/DAA520/FFFFFF.png?text=Onion+Soup",
    labels: [
      { category: "Cuisine", name: "French" },
      { category: "Meal Type", name: "Appetizer" },
      { category: "Meal Type", name: "Soup" },
      { category: "Difficulty", name: "Medium" },
    ],
    ingredients: [
      { name: "Yellow Onions", quantity: "4 large" },
      { name: "Beef Broth", quantity: "1 litre" },
      { name: "Dry White Wine", quantity: "100ml" },
      { name: "Butter", quantity: "2 tbsp" },
      { name: "Flour", quantity: "1 tbsp" },
      { name: "Bay Leaf", quantity: "1" },
      { name: "Thyme (fresh)", quantity: "1 sprig" },
      { name: "Baguette Slices", quantity: "4" },
      { name: "Gruyère Cheese (shredded)", quantity: "100g" },
      { name: "Salt", quantity: "to taste" },
      { name: "Black Pepper", quantity: "to taste" },
    ],
    instructions:
      "1. Slice onions thinly. In a large pot, melt butter over medium-low heat. Add onions and cook slowly for 30-40 minutes, stirring occasionally, until deeply caramelized and golden brown. This is crucial for flavor. 2. Stir in flour and cook for 2 minutes. 3. Deglaze with white wine, scraping up any browned bits. 4. Pour in beef broth, add bay leaf and thyme. Bring to a simmer, then cover and cook for 20 minutes. Season with salt and pepper. 5. Toast baguette slices. 6. Ladle soup into oven-safe bowls. Top each with a toasted baguette slice and a generous amount of Gruyère cheese. 7. Broil until cheese is melted and bubbly. Serve hot.",
  },
  {
    id: "rec-008", // Added unique ID
    name: "Mediterranean Quinoa Salad",
    description: "A light and refreshing salad packed with quinoa, vegetables, and a lemon-herb dressing.",
    image: "https://placehold.co/600x400/9ACD32/FFFFFF.png?text=Quinoa+Salad",
    labels: [
      { category: "Cuisine", name: "Mediterranean" },
      { category: "Meal Type", name: "Lunch" },
      { category: "Diet", name: "Vegan" },
      { category: "Diet", name: "Gluten-Free" },
      { category: "Difficulty", name: "Easy" },
    ],
    ingredients: [
      { name: "Quinoa", quantity: "150g" },
      { name: "Cucumber", quantity: "1 medium" },
      { name: "Cherry Tomatoes", quantity: "200g" },
      { name: "Red Onion", quantity: "0.5 small" },
      { name: "Kalamata Olives", quantity: "50g" },
      { name: "Fresh Parsley", quantity: "a handful" },
      { name: "Lemon Juice", quantity: "3 tbsp" },
      { name: "Olive Oil", quantity: "4 tbsp" },
      { name: "Salt", quantity: "0.5 tsp" },
      { name: "Black Pepper", quantity: "0.25 tsp" },
    ],
    instructions:
      "1. Rinse quinoa thoroughly. Cook quinoa according to package directions (usually 1 part quinoa to 2 parts water/broth). Let cool. 2. Dice cucumber, halve cherry tomatoes, thinly slice red onion, and chop parsley. 3. In a large bowl, combine cooked and cooled quinoa with all chopped vegetables, olives, and parsley. 4. In a small bowl, whisk together lemon juice, olive oil, salt, and pepper to make the dressing. 5. Pour dressing over the salad and toss gently to combine. Serve chilled.",
  },
  {
    id: "rec-009", // Added unique ID
    name: "Sheet Pan Sausage and Veggies",
    description: "An easy one-pan dinner with roasted sausage and colorful vegetables.",
    image: "https://placehold.co/600x400/FF8C00/FFFFFF.png?text=Sheet+Pan",
    labels: [
      { category: "Meal Type", name: "Dinner" },
      { category: "Cooking Method", name: "Roast" },
      { category: "Difficulty", name: "Easy" },
      { category: "Diet", name: "Meat" },
    ],
    ingredients: [
      { name: "Italian Sausage (links)", quantity: "400g" },
      { name: "Bell Peppers (mixed colors)", quantity: "2" },
      { name: "Zucchini", quantity: "1 medium" },
      { name: "Red Onion", quantity: "1 medium" },
      { name: "Broccoli Florets", quantity: "200g" },
      { name: "Olive Oil", quantity: "3 tbsp" },
      { name: "Dried Italian Herbs", quantity: "1 tsp" },
      { name: "Garlic Powder", quantity: "0.5 tsp" },
      { name: "Salt", quantity: "to taste" },
      { name: "Black Pepper", quantity: "to taste" },
    ],
    instructions:
      "1. Preheat oven to 200°C (390°F). Line a large baking sheet with parchment paper. 2. Slice sausages into 2.5 cm (1 inch) pieces. Chop all vegetables into similar-sized pieces. 3. In a large bowl, combine sausages and vegetables. Drizzle with olive oil, sprinkle with Italian herbs, garlic powder, salt, and pepper. Toss to coat evenly. 4. Spread the mixture in a single layer on the prepared baking sheet. Ensure not to overcrowd the pan for even roasting. 5. Roast for 25-35 minutes, stirring halfway through, until vegetables are tender and slightly caramelized, and sausage is cooked through. Serve hot.",
  },
  {
    id: "rec-010", // Added unique ID
    name: "Classic Pancakes with Berries",
    description: "Fluffy homemade pancakes, perfect for breakfast or brunch, topped with fresh berries.",
    image: "https://placehold.co/600x400/87CEEB/FFFFFF.png?text=Pancakes",
    labels: [
      { category: "Meal Type", name: "Breakfast" },
      { category: "Meal Type", name: "Brunch" },
      { category: "Diet", name: "Vegetarian" },
      { category: "Difficulty", name: "Easy" },
    ],
    ingredients: [
      { name: "All-Purpose Flour", quantity: "150g" },
      { name: "Baking Powder", quantity: "1.5 tsp" },
      { name: "Granulated Sugar", quantity: "1 tbsp" },
      { name: "Salt", quantity: "0.5 tsp" },
      { name: "Milk", quantity: "200ml" },
      { name: "Egg", quantity: "1 large" },
      { name: "Melted Butter", quantity: "2 tbsp" },
      { name: "Vanilla Extract", quantity: "0.5 tsp" },
      { name: "Fresh Berries (mixed)", quantity: "100g" },
      { name: "Maple Syrup", quantity: "to serve" },
    ],
    instructions:
      "1. In a large bowl, whisk together flour, baking powder, sugar, and salt. 2. In a separate bowl, whisk together milk, egg, melted butter, and vanilla extract. 3. Pour the wet ingredients into the dry ingredients and whisk until just combined. Do not overmix; lumps are okay. 4. Heat a lightly oiled griddle or non-stick pan over medium heat. 5. Pour about 60ml (1/4 cup) of batter per pancake onto the hot griddle. 6. Cook for 2-3 minutes per side, or until bubbles form on the surface and edges are set, then flip and cook until golden brown. 7. Serve immediately with fresh berries and maple syrup.",
  },
];